PROJECT=bootheader
MCU=atmega8
I2CDEV=1
CC=avr-gcc
OBJCOPY=avr-objcopy
CFLAGS=-g -mmcu=$(MCU) -Wall -Wstrict-prototypes -Os -mcall-prologues -W

$(PROJECT).hex: $(PROJECT) 
	$(OBJCOPY) -R .eeprom -O ihex $< $@

$(PROJECT): $(PROJECT).o
	$(CC) $(CFLAGS) -o $@ -Wl,-Map,$(PROJECT).map $<

$(PROJECT).s: $(PROJECT).c
	$(CC) $(CFLAGS) -S $<

clean:
	rm -f *.map *.hex $(PROJECT) *.o *.s *~ 

load: $(PROJECT).hex
	i2cloader -d $(I2CDEV) -f $(PROJECT).hex -s 0102FF -e FF -smbusdelay
