###########################################################################
#
# Tachometer/Motor Controller Makefile
#
###########################################################################

TARGET	= Tachometer

COMMON_OBJS = a2d_8.o Timer.o UART.o Hardware.o Tach.o

include ../Rules.mk

