###########################################################################
#
# Simple-Servo Makefile
#
###########################################################################

TARGET	= Simple-Servo

COMMON_OBJS = a2d_8.o Timer.o UART.o Hardware.o

include ../Rules.mk

