###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= RC-Test

COMMON_OBJS = lcd-api.o lcd-hal-avr.o lcd-stdio.o Log.o RCInput.o Delay.o Timer.o UART.o Hardware.o

include ../Rules.mk

