###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= LCD-Test

COMMON_OBJS = lcd-api.o lcd-hal-avr.o Delay.o Timer.o UART.o Hardware.o

#COMMON_OBJS = lcd.o Delay.o Timer.o UART.o Hardware.o

include ../Rules.mk

