#!/bin/bash
# Copyright(C) 2006 Jochen Roessner <jochen@lugrot.de>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 

modprobe -r lp
modprobe -r ppdev
modprobe -r i2c-dev
modprobe -r i2c-parport
modprobe -r parport_pc
modprobe -r parport
if [ "$1" == "1" ];then exit 0;fi
sleep 1
modprobe i2c-parport type=3
modprobe i2c-dev
sleep 2
chmod 666 /dev/i2c-0
chmod 666 /dev/i2c-1


