###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= Simple-Flasher

COMMON_OBJS = Delay.o Timer.o

include ../Rules.mk

