###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= int6

COMMON_OBJS = Delay.o Timer.o UART.o Hardware.o Log.o

include ../Rules.mk

