###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= ArgTest

COMMON_OBJS = Args.o Delay.o Timer.o UART.o Hardware.o

include ../Rules.mk

