###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= Flash-LED

COMMON_OBJS = a2d_8.o Delay.o Timer.o UART.o Hardware.o

include ../Rules.mk
