###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= QD-Test

COMMON_OBJS = QD.o Delay.o Timer.o UART.o Hardware.o

include ../Rules.mk

