#!/bin/bash

# Script written to monitor and control the DATA robot by Sawyer Larkin

NAME=`basename $0`

display_usage ()
{
  echo "Usage: $NAME [options]"  1>&2
  echo "" 1>&2
  echo "Powers off the BeagleBoard Trainer Board on the DATA robot, if it's currently powered." 1>&2
  echo "" 1>&2
  echo "  -h Print this message" 1>&2
	exit 1	
}

while getopts "h" opt
do
  case ${opt} in
    h )
      display_usage
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      display_usage
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      display_usage
      ;;
  esac
done
shift $((OPTIND -1))

# Chip gpio_162, linux gpio_130
POWER_IO=130
POWER_GPIO=gpio$POWER_IO

if [[ ! -d "/sys/class/gpio/$POWER_GPIO" ]]
then 
  echo $POWER_IO > /sys/class/gpio/export
  sleep 0.5
fi

if [[ ! -d "/sys/class/gpio/$POWER_GPIO" ]]
then 
  echo "Error opening GPIO!"
  exit 1
fi

DIRECTION=`cat /sys/class/gpio/$POWER_GPIO/direction`

if [[ $DIRECTION != "out" ]]
then 
  echo out > /sys/class/gpio/$POWER_GPIO/direction
fi

echo 0 > /sys/class/gpio/$POWER_GPIO/value
