#!/bin/bash

# Script written to monitor and control the DATA robot by Sawyer Larkin

I2C_BUS=1
I2C_BOARD=6

while [ true ]
do
  echo "------------------------------------------------------"
  echo -n "Left Encoder:   "
  i2cget -y $I2C_BUS $I2C_BOARD 0x6 w
  echo -n "Right Encoder:  "
  i2cget -y $I2C_BUS $I2C_BOARD 0x8 w
  echo -n "Stasis Encoder: "
  i2cget -y $I2C_BUS $I2C_BOARD 0xA w
  echo
  sleep 0.25
done
