#!/bin/bash

NAME=`basename $0`

# Script written to monitor and control the DATA robot by Sawyer Larkin

NAME=`basename $0`

display_usage() { 
  echo "Usage: $NAME [options] file" 1>&2
  echo "" 1>&2
	echo "Uploads a hex file to the Front Shell 328p on the DATA robot, via I2C." 1>&2
  echo "" 1>&2
	echo "If no I2C setup options are specified they will attempt to be set" 1>&2
	echo "by environment variables:" 1>&2
	echo "DATA_BASE_I2C_DEV and DATA_FRONT_I2C_BL_ADDR" 1>&2
	echo "" 1>&2
  echo "  file  Name of the file to upload" 1>&2
  echo "  -a    I2C board address" 1>&2
  echo "  -d    I2C device name" 1>&2
  echo "  -h    Print this message" 1>&2
  exit 1
} 

INVALID=INVALID
VERBOSE=0

DEV=${DATA_BASE_I2C_DEV:-$INVALID}
ADDR=${DATA_FRONT_I2C_BL_ADDR:-$INVALID}

while getopts "a:d:hv" opt
do
  case ${opt} in
    a )
      ADDR=$OPTARG
      ;;
    d )
      DEV=$OPTARG
      ;;
    h )
      display_usage
      ;;
    v )
      VERBOSE=1
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      display_usage
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      display_usage
      ;;
  esac
done
shift $((OPTIND -1))

if [[ $# -ne 1 ]]
then
  echo "Error: incorrect number of arguments! Please specify the file to write."
  display_usage
  exit 1
fi

FILE=$1

if [[ ! -f $FILE ]]
then
  echo "Error: $FILE is not a file!"
  display_usage
fi

if ! [[ $ADDR =~ ^[0-9xXaAbBcCdDeEfF]+$ ]]
then
  echo "No valid I2C board address specified!" 1>&2
  echo "I2C Board Address: $ADDR" 1>&2
  display_usage
fi

if [[ $DEV = $INVALID ]]
then
  echo "No valid I2C bus device specified!" 1>&2
  echo "I2C Bus Device: $DEV" 1>&2
  display_usage
fi

if [[ VERBOSE -ne 0 ]]
then
  echo "I2C Device Name:   $DEV"
  echo "I2C Board Address: $ADDR"
  echo "Filename: $FILE"
fi

shell_reset

twiboot -d $DEV -a $ADDR -p1 -w flash:$FILE
