#!/bin/bash

# Script written to monitor and control the DATA robot by Sawyer Larkin

I2C_BUS=1
I2C_BOARD=6
LIN_VEL_REG=2

TIME_COUNT=4

while [ true ]
do
  for ((i=1;i<=$TIME_COUNT;i++))
  do
    # i2cset -y BUS BOARD VEL_REG LinLow LinHigh AngLow AngHigh i
    i2cset -y $I2C_BUS $I2C_BOARD $LIN_VEL_REG 0x00 0x60 0x00 0x00 i
    echo "------------------------------------------------------"
    echo -n "System Time:      "
    i2cget -y $I2C_BUS $I2C_BOARD 0xC w
    echo -n "Linear Velocity:  "
    i2cget -y $I2C_BUS $I2C_BOARD 0x2 w
    echo -n "Angular Velocity: "
    i2cget -y $I2C_BUS $I2C_BOARD 0x4 w
#     echo
#     echo -n "Left Encoder:     "
#     i2cget -y 1 0x6 0x5 w
#     echo -n "Right Encoder:    "
#     i2cget -y 1 0x6 0x7 w
#     echo -n "Encoder Time:     "
#     i2cget -y 1 0x6 0x9 w
#     echo
    echo
    sleep 0.5
  done
  
  for ((i=1;i<=$TIME_COUNT;i++))
  do
    # i2cset -y BUS BOARD VEL_REG LinLow LinHigh AngLow AngHigh i
    i2cset -y $I2C_BUS $I2C_BOARD $LIN_VEL_REG 0x00 0x60 0x00 0x40 i
    echo "------------------------------------------------------"
    echo -n "System Time:      "
    i2cget -y $I2C_BUS $I2C_BOARD 0xC w
    echo -n "Linear Velocity:  "
    i2cget -y $I2C_BUS $I2C_BOARD 0x2 w
    echo -n "Angular Velocity: "
    i2cget -y $I2C_BUS $I2C_BOARD 0x4 w
    echo
    sleep 0.5
  done
done
