#!/bin/bash

# Script written to monitor and control the DATA robot by Sawyer Larkin

I2C_BUS=1
I2C_BOARD=6

while [ true ]
do
  echo "------------------------------------------------------"
  echo -n "Linear Velocity:  "
  i2cget -y $I2C_BUS $I2C_BOARD 0x2 w
  echo -n "Angular Velocity: "
  i2cget -y $I2C_BUS $I2C_BOARD 0x4 w
  echo
  sleep 0.25
done
