#!/bin/bash

# Script written to monitor and control the DATA robot by Sawyer Larkin

I2C_BUS=1
I2C_BOARD=6
LIN_VEL_REG=2

TIME_COUNT=10

for ((i=1;i<=$TIME_COUNT;i++))
do
  # i2cset -y BUS BOARD VEL_REG LinLow LinHigh AngLow AngHigh i
  i2cset -y $I2C_BUS $I2C_BOARD $LIN_VEL_REG 0x00 0x60 0x00 0x00 i
  sleep 0.5
done

i2cset -y $I2C_BUS $I2C_BOARD $LIN_VEL_REG 0x00 0x00 0x00 0x00 i
