###########################################################################
#
# Simple-Flasher Makefile
#
###########################################################################

TARGET	= i2c-test

COMMON_OBJS = Delay.o Timer.o UART.o Hardware.o

include ../Rules.mk

